theme: jekyll-theme-merlot
title: The Hanoi Hound
description: A one size fit all blog thing, but honestly, I rather code the whole thing in CSS and HTML, maybe even throw in some JS. Jekyll is so damn complicated yet simple at the same time. It makes no damn sense and I do not want to deal. Rather spend that time figuring out the multiple choice text-based RPG I am working on.
